name: debugger-action
on:
  workflow_dispatch:
  schedule:
    - cron: 0 19 1 * *
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
